# -*- coding: utf-8 -*-
"""Копия блокнота "Парсинг_Телеграм.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FFo5-ickTdXzLOw9f3kXCtHLEm0nLlQT
"""

!pip install -q streamlit

pip install telethon

import pandas as pd
from telethon.sync import TelegramClient

api_id = 29319788
api_hash = 'ea963474d7ee9fac389866a196023e84'
phone = 'ваш номер телефона, привязанный к профилю'
 
client = TelegramClient(phone, api_id, api_hash)

await client.start()
print(await client.get_me())

name = 'Настя' 
chat = 't.me/+KxlX36pb-3hjMjRi'

data = [] 

async with TelegramClient(name, api_id, api_hash) as client:
    async for message in client.iter_messages(chat, limit=100):
        data.append([message.from_id.user_id, message.text])


df = pd.DataFrame(data, columns=['user_id', 'text'])

df

"""Обучение"""

!pip install transformers

from transformers import pipeline

model=pipeline("sentiment-analysis",   
                      "blanchefort/rubert-base-cased-sentiment")

df_model = df.copy()

lst = []
for i in df_model["text"]:
  lst.append(model(str(i))[0]["label"])
df_model["Sentinent"]=pd.DataFrame(lst)
df_model

"""Графики"""

import matplotlib.pyplot as plt
import seaborn as sns

df_N = df_model[df_model["Sentinent"]=="NEGATIVE"]
df_n =df_N.user_id.value_counts().sort_index()
df_n.plot.bar(edgecolor='k', alpha=0.9, stacked = True, cmap="viridis")
plt.title("Самые негативные user_id	")

df_N

df_P = df_model[df_model["Sentinent"]=="POSITIVE"]
df_p =df_P.user_id.value_counts().sort_index()
df_p.plot.bar(edgecolor='k', alpha=0.9, stacked = True, cmap="viridis")
plt.title("Самые позитивные user_id")

df_P

df_s = df_model.groupby(["Sentinent"])["user_id"].count()
df_s.plot.bar(edgecolor='k', color = "navy", alpha=0.9)
plt.title("Количество видов сообщений")

